package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anuncios generated by hbm2java
 */
public class Anuncios  implements java.io.Serializable {


     private Integer idAnuncio;
     private float coste;
     private String anunciante;
     private Date fechaInicio;
     private Date fechaFin;
     private String multimedia;

    public Anuncios() {
    }

    public Anuncios(float coste, String anunciante, Date fechaInicio, Date fechaFin, String multimedia) {
       this.coste = coste;
       this.anunciante = anunciante;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.multimedia = multimedia;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public float getCoste() {
        return this.coste;
    }
    
    public void setCoste(float coste) {
        this.coste = coste;
    }
    public String getAnunciante() {
        return this.anunciante;
    }
    
    public void setAnunciante(String anunciante) {
        this.anunciante = anunciante;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getMultimedia() {
        return this.multimedia;
    }
    
    public void setMultimedia(String multimedia) {
        this.multimedia = multimedia;
    }




}


