package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cupones generated by hbm2java
 */
public class Cupones  implements java.io.Serializable {


     private String numeroCupon;
     private String descCupon;
     private Date fechaFin;
     private Date fechaInicio;
     private Set reservases = new HashSet(0);

    public Cupones() {
    }

	
    public Cupones(String numeroCupon, String descCupon, Date fechaFin, Date fechaInicio) {
        this.numeroCupon = numeroCupon;
        this.descCupon = descCupon;
        this.fechaFin = fechaFin;
        this.fechaInicio = fechaInicio;
    }
    public Cupones(String numeroCupon, String descCupon, Date fechaFin, Date fechaInicio, Set reservases) {
       this.numeroCupon = numeroCupon;
       this.descCupon = descCupon;
       this.fechaFin = fechaFin;
       this.fechaInicio = fechaInicio;
       this.reservases = reservases;
    }
   
    public String getNumeroCupon() {
        return this.numeroCupon;
    }
    
    public void setNumeroCupon(String numeroCupon) {
        this.numeroCupon = numeroCupon;
    }
    public String getDescCupon() {
        return this.descCupon;
    }
    
    public void setDescCupon(String descCupon) {
        this.descCupon = descCupon;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


