package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private Integer idReserva;
     private Cupones cupones;
     private Usuarios usuarios;
     private Viajes viajes;
     private Date FReserva;
     private int costeFinal;
     private Set valoracioneses = new HashSet(0);

    public Reservas() {
    }

	
    public Reservas(Cupones cupones, Usuarios usuarios, Viajes viajes, Date FReserva, int costeFinal) {
        this.cupones = cupones;
        this.usuarios = usuarios;
        this.viajes = viajes;
        this.FReserva = FReserva;
        this.costeFinal = costeFinal;
    }
    public Reservas(Cupones cupones, Usuarios usuarios, Viajes viajes, Date FReserva, int costeFinal, Set valoracioneses) {
       this.cupones = cupones;
       this.usuarios = usuarios;
       this.viajes = viajes;
       this.FReserva = FReserva;
       this.costeFinal = costeFinal;
       this.valoracioneses = valoracioneses;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Cupones getCupones() {
        return this.cupones;
    }
    
    public void setCupones(Cupones cupones) {
        this.cupones = cupones;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Viajes getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Viajes viajes) {
        this.viajes = viajes;
    }
    public Date getFReserva() {
        return this.FReserva;
    }
    
    public void setFReserva(Date FReserva) {
        this.FReserva = FReserva;
    }
    public int getCosteFinal() {
        return this.costeFinal;
    }
    
    public void setCosteFinal(int costeFinal) {
        this.costeFinal = costeFinal;
    }
    public Set getValoracioneses() {
        return this.valoracioneses;
    }
    
    public void setValoracioneses(Set valoracioneses) {
        this.valoracioneses = valoracioneses;
    }




}


