package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seguros generated by hbm2java
 */
public class Seguros  implements java.io.Serializable {


     private Integer idSeguro;
     private int empresa;
     private int tipo;
     private int descripcion;
     private Set viajeses = new HashSet(0);

    public Seguros() {
    }

	
    public Seguros(int empresa, int tipo, int descripcion) {
        this.empresa = empresa;
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public Seguros(int empresa, int tipo, int descripcion, Set viajeses) {
       this.empresa = empresa;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.viajeses = viajeses;
    }
   
    public Integer getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(Integer idSeguro) {
        this.idSeguro = idSeguro;
    }
    public int getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(int empresa) {
        this.empresa = empresa;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public int getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(int descripcion) {
        this.descripcion = descripcion;
    }
    public Set getViajeses() {
        return this.viajeses;
    }
    
    public void setViajeses(Set viajeses) {
        this.viajeses = viajeses;
    }




}


