package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seguros generated by hbm2java
 */
public class Seguros  implements java.io.Serializable {


     private Integer idSeguro;
     private String empresa;
     private String tipo;
     private String descripcion;
     private Set viajeses = new HashSet(0);

    public Seguros() {
    }

	
    public Seguros(String empresa, String tipo, String descripcion) {
        this.empresa = empresa;
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public Seguros(String empresa, String tipo, String descripcion, Set viajeses) {
       this.empresa = empresa;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.viajeses = viajeses;
    }
   
    public Integer getIdSeguro() {
        return this.idSeguro;
    }
    
    public void setIdSeguro(Integer idSeguro) {
        this.idSeguro = idSeguro;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getViajeses() {
        return this.viajeses;
    }
    
    public void setViajeses(Set viajeses) {
        this.viajeses = viajeses;
    }




}


