package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1



/**
 * Valoraciones generated by hbm2java
 */
public class Valoraciones  implements java.io.Serializable {


     private Integer idValoracion;
     private Reservas reservas;
     private int puntuacion;
     private String descripcion;

    public Valoraciones() {
    }

    public Valoraciones(Reservas reservas, int puntuacion, String descripcion) {
       this.reservas = reservas;
       this.puntuacion = puntuacion;
       this.descripcion = descripcion;
    }
   
    public Integer getIdValoracion() {
        return this.idValoracion;
    }
    
    public void setIdValoracion(Integer idValoracion) {
        this.idValoracion = idValoracion;
    }
    public Reservas getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Reservas reservas) {
        this.reservas = reservas;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


