package entidades;
// Generated 20-abr-2021 19:53:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viajes generated by hbm2java
 */
public class Viajes  implements java.io.Serializable {


     private Integer idViaje;
     private Seguros seguros;
     private Usuarios usuarios;
     private Date horaSalida;
     private Date horaLlegada;
     private String origen;
     private String destino;
     private float coste;
     private int numPasajeros;
     private Set reservases = new HashSet(0);

    public Viajes() {
    }

	
    public Viajes(Seguros seguros, Usuarios usuarios, Date horaSalida, Date horaLlegada, String origen, String destino, float coste, int numPasajeros) {
        this.seguros = seguros;
        this.usuarios = usuarios;
        this.horaSalida = horaSalida;
        this.horaLlegada = horaLlegada;
        this.origen = origen;
        this.destino = destino;
        this.coste = coste;
        this.numPasajeros = numPasajeros;
    }
    public Viajes(Seguros seguros, Usuarios usuarios, Date horaSalida, Date horaLlegada, String origen, String destino, float coste, int numPasajeros, Set reservases) {
       this.seguros = seguros;
       this.usuarios = usuarios;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.origen = origen;
       this.destino = destino;
       this.coste = coste;
       this.numPasajeros = numPasajeros;
       this.reservases = reservases;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public Seguros getSeguros() {
        return this.seguros;
    }
    
    public void setSeguros(Seguros seguros) {
        this.seguros = seguros;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public float getCoste() {
        return this.coste;
    }
    
    public void setCoste(float coste) {
        this.coste = coste;
    }
    public int getNumPasajeros() {
        return this.numPasajeros;
    }
    
    public void setNumPasajeros(int numPasajeros) {
        this.numPasajeros = numPasajeros;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }




}


